config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  # Routes to leave
  get 'leaves/index' => 'leaves#index', :as => 'leaves_index'
  get 'leaves/show/:id' => 'leaves#show', :as => 'leaves_show'
  get 'leaves/new' => 'leaves#new', :as => 'leaves_new'
  get 'leaves/create_sector' => 'leaves#create_sector', :as => 'leaves_create_sector'
  post 'leaves/create' => 'leaves#create', :as => 'leaves_create'

  # Routes to entry
  get 'entries/index' => 'entries#index', :as => 'entries_index'
  get 'entries/show/:id' => 'entries#show', :as => 'entries_show'
  get 'entries/new' => 'entries#new', :as => 'entries_new'
  post 'entries/create' => 'entries#create', :as => 'entries_create'
  get 'entries/receive/:id' => 'entries#receive', :as => 'entries_receive'
  post 'entries/update/:id' => 'entries#update', :as => 'entries_update'

  # Routes to material
  get 'materials/index' => 'materials#index', :as => 'materials_index'
  get 'materials/new' => 'materials#new', :as => 'materials_new'
  post 'materials/create' => 'materials#create', :as => 'materials_create'
  get 'materials/edit/:id' => 'materials#edit', :as => 'materials_edit'
  patch 'materials/update/:id' => 'materials#update', :as => 'materials_update'
  get 'materials/destroy/:id' => 'materials#destroy', :as => 'materials_destroy'

  # Routes to user
  get 'users/index' => 'users#index', :as => 'users_index'
  get 'users/active/:id' => 'users#active', :as => 'users_active'
  get 'users/new' => 'users#new', :as => 'users_new'
  post 'users/create' => 'users#create', :as => 'users_create'
  get 'users/edit' => 'users#edit', :as => 'users_edit'
  patch 'users/update' => 'users#update', :as => 'users_update'
  get 'users/destroy' => 'users#destroy', :as => 'users_destroy'

  # Session routs
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'init_session' => 'sessions#create', :as => 'sessions_create'

  # home page route
  get 'home/index' => 'home#index', :as => 'home'
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :requested_user, class_name: 'User'
  belongs_to :user_receive, class_name: 'User', optional: true
  has_many :material_entry, autosave: true

  # Exception messages
  INVALID_USER = 'Usuário não pode ser nulo'.freeze
  INVALID_DATE = 'Data não pode ser nula '.freeze

  # Validates
  validates :requested_user, presence: { message: INVALID_USER }
  validates :requested_date, presence: { message: INVALID_DATE }
  validates :user_receive, presence: { message: INVALID_USER }, on: :update
  validates :receive_date, presence: { message: INVALID_DATE }, on: :update

  validate :validates_material_entry, on: :update

  def validates_material_entry
    material_entry.each do |material|
      if material.amount_received.nil?
        errors.add(:material_entry, 'Quantidade recebida deve ser preenchida')
        break
      end
    end
  end
end

app/controllers/entries_controller.rb
# controller class to manager entry and entry_material models, only:
# Create, Update and View
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    # create form
    @materials = Material.all
  end

  def receive
    # update form
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
    @entry.update(receive_date: params[:entry][:receive_date],
                  user_receive: current_user)

    update_material_entry(@entry)
    save(@entry, 'Atualizado com sucesso!', :receive)
  end

  def create
    @materials = Material.all
    entry = Entry.new(requested_date: params[:entry][:requested_date],
                      requested_user: current_user)
    create_material_entry(entry, (params[:material][:id].as_json.size - 1))
    save(entry, 'Cadastrado com sucesso!', :new)
  end

  private

  def create_material_entry(entry, maximum)
    (0..maximum).each do |id|
      entry.material_entry
           .build(requested_amount: params[:material][:amount][id.to_s],
                  material_id: params[:material][:id][id.to_s])
    end
  end

  def update_material_entry(entry)
    (0..(params[:material][:id].as_json.size - 1)).each do |id|
      entry.material_entry[id]
           .amount_received = params[:material][:amount][id.to_s]
    end
  end

  def save(entry, message, location)
    if entry.save
      redirect_to entries_index_path, flash: { success: message }
    else
      ocurred_errors(entry)
      render location
    end
  end
end

app/views/entries/index.html.erb
<h1>Todos as Entradas</h1>

<%= link_to 'Cadastrar Novo', entries_new_path %>
<table>
  <tr>
    <th>Data de Solicitação</th>
    <th>Operador</th>
    <th>Status</th>
    <th>Efetuar recebimento</th>
    <th>Visualizar</th>
  </tr>
  <% @entries.each do |entry|%>
    <tr>
      <td><%= entry.requested_date %></td>
      <td><%= entry.requested_user.email %></td>
      <td>
      <% if entry.receive_date.nil? %>
        Aguardando Entrega
      <% else %>
        Concluído
      <% end %>
        
      </td>

      <td>
      <% if entry.receive_date.nil? %>
        <%= link_to image_tag('icon_edit.png'), entries_receive_path(entry.id) %>
      <% end %>
        
      </td>
      <td><%= link_to image_tag('icon_view.png'), entries_show_path(entry.id) %></td>
    </tr>
  <% end %>
</table>

app/views/entries/new.html.erb
<h1>Cadastrar novo Entrada de Material</h1>
<%= form_tag entries_create_path do %>
  <p>
    <%= label_tag :requested_date, 'Data de Recebimento:' %><br />
    <%= datetime_local_field(:entry, :requested_date) %><br />
  </p>

  <p id="new_material_list">
      <%= label_tag :material, 'Material 1:' %><br />
      <%= select_tag 'material[id][0]', options_from_collection_for_select(@materials, 'id', 'name') %><br />
      <%= label_tag :amount, 'Quantidade:' %><br />
      <%= number_field_tag 'material[amount][0]' %><br /><br />
  </p>
  <p>
    <input type="button" id="new_material" value="adicionar" class="btn btn-info" />
  </p>
  <%= submit_tag "Salvar", class: 'btn btn-success' %>
<% end %>

app/views/entries/receive.html.erb
<h1>Cadastrar novo Entrada de Material</h1>
<%= form_tag entries_update_path(params[:id]) do %>
  <p>
    <b><%= label_tag :requested_date, 'Data do Pedido:' %></b>:
    <%= label_tag :requested_date, @entry.requested_date %><br />
  </p>

  <p>
      <b><%= label_tag :receive_date, 'Data de Recebimento:' %></b><br />
      <%= datetime_local_field(:entry, :receive_date) %><br />
  </p>

  <table>
    <tr>
      <th>Material</th>
      <th>Solicitado</th>
      <th>Recebido</th>
    </tr>
    <% @entry.material_entry.each_with_index do |entry,index|%>
      <tr>
        <td><%= entry.material.name %></td>
        <td><%= entry.requested_amount %></td>
        <td>
          <%= number_field_tag "material[amount][#{index}]" %>
          <%= hidden_field_tag "material[id][#{index}]", entry.id %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= submit_tag "Update", class: 'pull-right btn btn-default btn-success' %>
<% end %>

app/views/entries/show.html.erb
<h1>Entrada de Material</h1>

<p><strong>Solicitante:</strong> <%= @entry.requested_user.email %></p>
<p><strong>Data de Solicitação:</strong> <%= @entry.requested_date %></p>
<p><strong>Data do Recebimento:</strong> <%= @entry.receive_date %></p>
<p><strong>Usuário que Recebeu:</strong> <%= @entry.user_receive.email unless @entry.user_receive.nil? %></p>
<p><strong>Material:</strong> 
  <table>
    <tr>
      <th>Material</th>
      <th>Quantidade Solicitada</th>
      <th>Quantidade Recebida</th>
    </tr>
    <% @entry.material_entry.each do |materials| %>
      <tr>
        <td><%= materials.material.name %></td>
        <td><%= materials.requested_amount %></td>
        <td><%= materials.amount_received %></td>
      </tr>
    <% end %>
  </table>
</p>