config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  # Routes to leave
  get 'leaves/index' => 'leaves#index', :as => 'leaves_index'
  get 'leaves/show/:id' => 'leaves#show', :as => 'leaves_show'
  get 'leaves/new' => 'leaves#new', :as => 'leaves_new'
  get 'leaves/create_sector' => 'leaves#create_sector', :as => 'leaves_create_sector'
  post 'leaves/create' => 'leaves#create', :as => 'leaves_create'

  # Routes to entry
  get 'entries/index' => 'entries#index', :as => 'entries_index'
  get 'entries/show/:id' => 'entries#show', :as => 'entries_show'
  get 'entries/new' => 'entries#new', :as => 'entries_new'
  post 'entries/create' => 'entries#create', :as => 'entries_create'
  get 'entries/receive/:id' => 'entries#receive', :as => 'entries_receive'
  post 'entries/update/:id' => 'entries#update', :as => 'entries_update'

  # Routes to material
  get 'materials/index' => 'materials#index', :as => 'materials_index'
  get 'materials/new' => 'materials#new', :as => 'materials_new'
  post 'materials/create' => 'materials#create', :as => 'materials_create'
  get 'materials/edit/:id' => 'materials#edit', :as => 'materials_edit'
  patch 'materials/update/:id' => 'materials#update', :as => 'materials_update'
  get 'materials/destroy/:id' => 'materials#destroy', :as => 'materials_destroy'

  # Routes to user
  get 'users/index' => 'users#index', :as => 'users_index'
  get 'users/active/:id' => 'users#active', :as => 'users_active'
  get 'users/new' => 'users#new', :as => 'users_new'
  post 'users/create' => 'users#create', :as => 'users_create'
  get 'users/edit' => 'users#edit', :as => 'users_edit'
  patch 'users/update' => 'users#update', :as => 'users_update'
  get 'users/destroy' => 'users#destroy', :as => 'users_destroy'

  # Session routs
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'init_session' => 'sessions#create', :as => 'sessions_create'

  # home page route
  get 'home/index' => 'home#index', :as => 'home'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  before_save :encrypt_password

  # Exception messages
  DIFERENT_PASSWORDS = 'Senhas Diferem'.freeze
  PASSWORD_CANT_BLANCK = 'Preencha a Senha'.freeze
  EMAIL_CANT_BLANCK = 'Preencha o Email'.freeze
  EMAIL_CAN_EXISTS = 'Email já cadastrado'.freeze

  # Validates
  validates :password, confirmation: { message: DIFERENT_PASSWORDS }
  validates :password, presence: { message: PASSWORD_CANT_BLANCK }, on: :create
  validates :email, presence: { message: EMAIL_CANT_BLANCK }
  validates :email, uniqueness: { message: EMAIL_CAN_EXISTS }

  # Model method to check user authenticate
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user &&
       user.password_hash == BCrypt::Engine.hash_secret(password,
                                                        user.password_salt)
      user
    end
  end

  def encrypt_password
    return unless password.present?
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

app/controllers/users_controller.rb
# controller class to manager CRUD user models
class UsersController < ApplicationController
  before_action :autenticated?

  def index
    @users = User.all
  end

  def active
    if User.exists?(params[:id])
      user = User.find(params[:id])
      user.update_attributes(active: 1)

      message = 'Ativado com sucesso!'
      redirect_to users_index_path, flash: { success: message }
    else
      message = 'Usuário não encontrado'
      redirect_to users_index_path, flash: { error: message }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      message = 'Cadastrado com sucesso!'
      redirect_to users_index_path, flash: { success: message }
    else
      ocurred_errors(@user)
      render :new
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      message = 'Dados atualizados com sucesso'
      redirect_to users_index_path, flash: { success: message }
    else
      ocurred_errors(@user)
      render :edit
    end
  end

  def edit
    @user = current_user
  end

  def destroy
    if User.all.where(active: 1).size != 1
      current_user.update_attributes(active: 0)
      session[:user_id] = nil
      redirect_to log_in_path, flash: { success: 'Usuário desativado' }
    else
      message = 'Impossível desativar último usuário do sistema'
      redirect_to home_path, flash: { error: message } if User.all.size == 1
    end
  end

  private

  def user_params
    params[:user].permit(:email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
# Base class with the users methods used by views
module UsersHelper
  def total_users
    User.all.size
  end
end

app/views/users/edit.html.erb
<h1>Editar dados</h1>

<%= form_for @user, url: users_update_path do |f| %>
  <%= f.label :email, 'Email' %><br />
  <%= f.text_field :email %><br />
  <%= f.label :password , 'Senha'%><br />
  <%= f.password_field :password %><br />
  <%= f.label :password_confirmation, 'Confirmação de Senha' %><br />
  <%= f.password_field :password_confirmation %><br />
  <%= f.submit 'Alterar'%>
<% end -%>

app/views/users/index.html.erb
<h1>Todos os Usuários</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Ativar</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td>
        <% if user.active.zero? %>
          <%= link_to 'Ativar', users_active_path(user.id)%>
        <% else %>
          Ativo
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Cadastrar novo membro</h1>
<%= form_for @user, url: users_create_path do |f| %>
  <p>
    <%= f.label :email, 'Email' %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password , 'Senha'%><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, 'Confirmação de Senha' %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="btn btn-default btn-success"><%= f.submit 'Salvar' %></p>
<% end %>