config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  # Routes to leave
  get 'leaves/index' => 'leaves#index', :as => 'leaves_index'
  get 'leaves/show/:id' => 'leaves#show', :as => 'leaves_show'
  get 'leaves/new' => 'leaves#new', :as => 'leaves_new'
  get 'leaves/create_sector' => 'leaves#create_sector', :as => 'leaves_create_sector'
  post 'leaves/create' => 'leaves#create', :as => 'leaves_create'

  # Routes to entry
  get 'entries/index' => 'entries#index', :as => 'entries_index'
  get 'entries/show/:id' => 'entries#show', :as => 'entries_show'
  get 'entries/new' => 'entries#new', :as => 'entries_new'
  post 'entries/create' => 'entries#create', :as => 'entries_create'
  get 'entries/receive/:id' => 'entries#receive', :as => 'entries_receive'
  post 'entries/update/:id' => 'entries#update', :as => 'entries_update'

  # Routes to material
  get 'materials/index' => 'materials#index', :as => 'materials_index'
  get 'materials/new' => 'materials#new', :as => 'materials_new'
  post 'materials/create' => 'materials#create', :as => 'materials_create'
  get 'materials/edit/:id' => 'materials#edit', :as => 'materials_edit'
  patch 'materials/update/:id' => 'materials#update', :as => 'materials_update'
  get 'materials/destroy/:id' => 'materials#destroy', :as => 'materials_destroy'

  # Routes to user
  get 'users/index' => 'users#index', :as => 'users_index'
  get 'users/active/:id' => 'users#active', :as => 'users_active'
  get 'users/new' => 'users#new', :as => 'users_new'
  post 'users/create' => 'users#create', :as => 'users_create'
  get 'users/edit' => 'users#edit', :as => 'users_edit'
  patch 'users/update' => 'users#update', :as => 'users_update'
  get 'users/destroy' => 'users#destroy', :as => 'users_destroy'

  # Session routs
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'init_session' => 'sessions#create', :as => 'sessions_create'

  # home page route
  get 'home/index' => 'home#index', :as => 'home'
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :material_entry
  has_many :material_leave

  # Exception messages
  INVALID_NAME = 'Preencha o nome do Produto'.freeze
  INVALID_AMOUNT = 'Preencha a quantidade inicial'.freeze
  AMOUT_IS_NUMERIC = 'Quantidade deve ser numérico'.freeze

  # Validates
  validates :name, presence: { message: INVALID_NAME }
  validates :initial_amount, presence: { message: INVALID_AMOUNT }, on: :create
  validates :initial_amount, numericality: { message: AMOUT_IS_NUMERIC }

  def total_amount
    total = initial_amount

    material_entry.each do |entry|
      total += entry.amount_received
    end

    material_leave.each do |leave|
      total -= leave.amount_received
    end
    total
  end
end

app/controllers/materials_controller.rb
# controller class to manager material models, only Create, Update and View
class MaterialsController < ApplicationController
  def index
    @materials = Material.all
  end

  def new
    @material = Material.new
  end

  def create
    @material = Material.new(product_params_new)
    if @material.save
      message = 'Cadastrado com sucesso!'
      redirect_to materials_index_path, flash: { notice: message }
    else
      ocurred_errors(@material)
      render :new
    end
  end

  def edit
    @material = Material.find(params[:id])
  end

  def update
    @material = Material.find(params[:id])
    if @material.update(product_params_update)
      message = 'Dados atualizados com sucesso'
      redirect_to materials_index_path, flash: { success: message }
    else
      ocurred_errors(@material)
      render :edit
    end
  end

  private

  def product_params_update
    params[:material].permit(:name)
  end

  def product_params_new
    params[:material].permit(:name, :initial_amount)
  end
end

app/views/materials/_all_material.html.erb
<table>
  <tr>
    <th>Nome</th>
    <th>Quantidade Disponível</th>
    <th>Alterar</th>
  </tr>
  <% @materials.each do |material|%>
    <tr>
    <td><%= material.name %></td>
    <td><%= material.total_amount %></td>
    <td><%= link_to image_tag('icon_edit.png'), materials_edit_path(material.id) %></td>
    </tr>
  <% end %>
</table>

app/views/materials/edit.html.erb
<h1>Alterar Material</h1>

<%= form_for @material, url: materials_update_path(@material.id) do |f| %>
  <%= f.label :name, 'Nome' %><br>
  <%= f.text_field :name %><br>
  <%= f.submit 'Alterar' %>

<% end %>

app/views/materials/index.html.erb
<h1>Todos os Materiais</h1>

<%= link_to 'Cadastrar Novo', materials_new_path %>
<%= render partial: "materials/all_material" %>

app/views/materials/new.html.erb
<h1>Cadastrar Material</h1>

<%= form_for @material, url: materials_create_path do |f| %>
  <%= f.label :name, 'Nome' %><br>
  <%= f.text_field :name %><br>
  <%= f.label :initial_amount , 'Quantidade'%><br>
  <%= f.text_field :initial_amount %><br>
  <%= f.submit 'Salvar'%>

<% end %>