config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  # Routes to leave
  get 'leaves/index' => 'leaves#index', :as => 'leaves_index'
  get 'leaves/show/:id' => 'leaves#show', :as => 'leaves_show'
  get 'leaves/new' => 'leaves#new', :as => 'leaves_new'
  get 'leaves/create_sector' => 'leaves#create_sector', :as => 'leaves_create_sector'
  post 'leaves/create' => 'leaves#create', :as => 'leaves_create'

  # Routes to entry
  get 'entries/index' => 'entries#index', :as => 'entries_index'
  get 'entries/show/:id' => 'entries#show', :as => 'entries_show'
  get 'entries/new' => 'entries#new', :as => 'entries_new'
  post 'entries/create' => 'entries#create', :as => 'entries_create'
  get 'entries/receive/:id' => 'entries#receive', :as => 'entries_receive'
  post 'entries/update/:id' => 'entries#update', :as => 'entries_update'

  # Routes to material
  get 'materials/index' => 'materials#index', :as => 'materials_index'
  get 'materials/new' => 'materials#new', :as => 'materials_new'
  post 'materials/create' => 'materials#create', :as => 'materials_create'
  get 'materials/edit/:id' => 'materials#edit', :as => 'materials_edit'
  patch 'materials/update/:id' => 'materials#update', :as => 'materials_update'
  get 'materials/destroy/:id' => 'materials#destroy', :as => 'materials_destroy'

  # Routes to user
  get 'users/index' => 'users#index', :as => 'users_index'
  get 'users/active/:id' => 'users#active', :as => 'users_active'
  get 'users/new' => 'users#new', :as => 'users_new'
  post 'users/create' => 'users#create', :as => 'users_create'
  get 'users/edit' => 'users#edit', :as => 'users_edit'
  patch 'users/update' => 'users#update', :as => 'users_update'
  get 'users/destroy' => 'users#destroy', :as => 'users_destroy'

  # Session routs
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'init_session' => 'sessions#create', :as => 'sessions_create'

  # home page route
  get 'home/index' => 'home#index', :as => 'home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="pt-br">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Almoxarifado FS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='alertContainer'>
    <% flash.each do |key, value| %>
      <div class='alert alert-<%= key %>'><%= value %></div>
    <% end %>
  </div>
	  <div id='user_nav'>
	  <% if current_user %>
	    Logged in as <%= current_user.email %>.
      <ul>
        <li>Usuários
          <ul>
            <li><%= link_to 'Mostrar Todos', users_index_path %></li>
            <li><%= link_to 'Cadastrar Novo', users_new_path %></li>
            <li><%= link_to 'Alterar Minha Conta', users_edit_path %></li>
            <% unless total_users == 1 %>
              <li><%= link_to 'Apagar minha conta', users_destroy_path, data: {confirm: 'Esta ação não poderá mais ser desfeita. Tem certeza que deseja continuar?'} %></li>
            <% end -%>
          </ul>
        </li>
        <li><%= link_to 'Materiais', materials_index_path %></li>
        <li><%= link_to 'Entradas', entries_index_path %></li>
        <li><%= link_to 'Retirada', leaves_index_path %></li>


        <li><%= link_to 'Log out', log_out_path %></li>
      </ul>
	  <% end %>
	</div>
    <%= yield %>
  </body>
</html>